# Generated by Django 3.1 on 2020-09-01 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instruction', models.TextField()),
                ('duration', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('passing_percent', models.IntegerField()),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_marks', models.FloatField(default=0.0)),
                ('marks', models.FloatField()),
                ('ques_random', models.BooleanField(default=False)),
                ('paid_exam', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('finalized_time', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('modified', models.DateField(default=django.utils.timezone.now)),
                ('examtype', models.CharField(choices=[('marathon', 'MARATHON'), ('single', 'SINGLE'), ('timer', 'TIMER')], default='marathon', max_length=50)),
                ('title_image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True)),
                ('question', models.TextField()),
                ('option1', models.TextField(blank=True)),
                ('option2', models.TextField(blank=True)),
                ('option3', models.TextField(blank=True)),
                ('option4', models.TextField(blank=True)),
                ('option5', models.TextField(blank=True)),
                ('option6', models.TextField(blank=True)),
                ('marks', models.FloatField(default=1.0)),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('explort', models.TextField(blank=True)),
                ('answer', models.IntegerField()),
                ('true_false', models.BooleanField(default=False)),
                ('fill_blank', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Started',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Started',
                'unique_together': {('exam', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Answered',
                'unique_together': {('question', 'user')},
            },
        ),
    ]
