# Generated by Django 3.1 on 2020-09-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='started',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='exam_finished',
            field=models.BooleanField(default=False),
        ),
    ]
