# Generated by Django 3.1 on 2020-08-14 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200813_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='created',
            field=models.DateField(default=datetime.date(2020, 8, 14)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 8, 14)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='finalized_time',
            field=models.DateField(default=datetime.date(2020, 8, 14)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='modified',
            field=models.DateField(default=datetime.date(2020, 8, 14)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 14)),
        ),
    ]
