# Generated by Django 3.1 on 2020-08-14 20:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0005_auto_20200814_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='created',
            field=models.DateField(default=datetime.date(2020, 8, 15)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 8, 15)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='finalized_time',
            field=models.DateField(default=datetime.date(2020, 8, 15)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='modified',
            field=models.DateField(default=datetime.date(2020, 8, 15)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 15)),
        ),
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
