# Generated by Django 3.1 on 2020-08-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20200815_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answered',
            options={'verbose_name_plural': 'Answered'},
        ),
    ]
