# Generated by Django 3.1 on 2020-08-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20200815_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answered',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='answered',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='answered',
            name='owner',
        ),
        migrations.AlterField(
            model_name='answered',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answered',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question'),
        ),
    ]
