# Generated by Django 3.1 on 2020-10-28 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20201017_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled_at',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='starts_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
