# Generated by Django 3.1 on 2020-10-28 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20201028_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='EventExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('eventType', models.CharField(choices=[('marathon', 'MARATHON'), ('single', 'SINGLE'), ('timer', 'TIMER')], default='marathon', max_length=50)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='starts_at',
        ),
    ]
