# Generated by Django 3.1 on 2020-08-15 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200815_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='finalized_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='modified',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
