# Generated by Django 3.1 on 2020-08-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20200815_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answered',
            name='answer',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
