# Generated by Django 3.1 on 2020-10-28 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0009_auto_20201028_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.eventexam'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('event', 'owner')},
        ),
    ]
