# Generated by Django 3.1 on 2020-08-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20200815_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='examtype',
            field=models.CharField(choices=[('marathon', 'MARATHON'), ('single', 'SINGLE'), ('timer', 'TIMER')], default='marathon', max_length=50),
        ),
    ]
