# Generated by Django 3.1 on 2020-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_exam_examtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='declare_result',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='finish_result',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='exam',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='negative_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='paid_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ques_random',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
