# Generated by Django 3.1 on 2020-08-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20200816_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='attempt_count',
        ),
    ]
