# Generated by Django 3.1 on 2020-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_remove_exam_attempt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
