# Generated by Django 3.1 on 2020-08-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20200816_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qtype_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='title_image_url',
            field=models.URLField(blank=True),
        ),
    ]
