# Generated by Django 3.1 on 2020-08-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20200816_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='negative_marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qtag_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='explort',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='fill_blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='true_false',
            field=models.BooleanField(default=False),
        ),
    ]
