# Generated by Django 3.1 on 2020-08-22 18:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0017_auto_20200816_1314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='started',
            unique_together={('exam', 'owner')},
        ),
    ]
