# Generated by Django 3.1 on 2020-08-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_remove_answered_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answered',
            name='answer',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
