# Generated by Django 3.1 on 2020-08-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_answered_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answered',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
