# Generated by Django 3.1 on 2020-08-26 20:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0019_auto_20200826_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('message', models.TextField()),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=5000)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('meta_title', models.TextField()),
                ('meta_desc', models.TextField()),
                ('timezone', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('sms', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
                ('guest_login', models.BooleanField(default=False)),
                ('front_end', models.BooleanField(default=False)),
                ('slides', models.SmallIntegerField()),
                ('translate', models.SmallIntegerField(default=0)),
                ('paid_exam', models.SmallIntegerField(default=1)),
                ('leader_board', models.BooleanField(default=True)),
                ('contact', models.TextField()),
                ('photo', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('modified_at', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
