# Generated by Django 3.1 on 2020-08-25 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0020_auto_20200825_1658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answered',
            unique_together={('question', 'user')},
        ),
    ]
