# Generated by Django 3.1 on 2020-08-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_answered_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answered',
            name='owner',
        ),
    ]
