# Generated by Django 3.1 on 2020-08-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
