# Generated by Django 3.1 on 2020-08-24 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_auto_20200824_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='updated_at',
        ),
    ]
