# Generated by Django 3.1 on 2020-08-24 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_auto_20200824_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cities',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
