# Generated by Django 3.1 on 2020-08-24 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_auto_20200824_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
