# Generated by Django 3.1 on 2020-08-24 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_auto_20200824_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
