# Generated by Django 3.1 on 2020-08-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_auto_20200824_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
