# Generated by Django 3.1 on 2020-08-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_auto_20200824_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group_name', models.CharField(max_length=255)),
            ],
        ),
    ]
