# Generated by Django 3.1 on 2020-08-24 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0033_bloodgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='cities',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
