# Generated by Django 3.1 on 2020-08-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0036_auto_20200824_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='user',
            new_name='owner',
        ),
    ]
