# Generated by Django 3.1 on 2020-08-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0037_auto_20200824_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='owner',
        ),
    ]
