# Generated by Django 3.1 on 2020-08-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0039_cities_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='owner',
            new_name='user',
        ),
    ]
