# Generated by Django 3.1 on 2020-08-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0040_auto_20200824_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='updated_at',
        ),
    ]
