# Generated by Django 3.1 on 2020-08-24 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0042_auto_20200824_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodgroup',
            options={'verbose_name_plural': 'Blood Group'},
        ),
        migrations.AddField(
            model_name='bloodgroup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
