# Generated by Django 3.1 on 2020-08-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0044_countries_currencies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencies',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
