# Generated by Django 3.1 on 2020-08-31 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20200825_1947'),
        ('exam', '0045_auto_20200824_0912'),
        ('exam', '0020_configuration_contact_feedback'),
    ]

    operations = [
    ]
