from django.urls import path
from .views import *

urlpatterns = [
    path('address/<int:id>', AddressRetrieveView.as_view()),
    path('address/new', AddressCreateView.as_view()),
    path('address/update/<int:id>', AddressUpdateView.as_view()),
    path('address/delete/<int:id>', AddressDeleteView.as_view()),
    path('config/<int:id>', ConfigurationRetrieveView.as_view()),
    path('config/new', ConfigurationCreateView.as_view()),
    path('config/update/<int:id>', ConfigurationUpdateView.as_view()),
    path('config/delete/<int:id>', ConfigurationDeleteView.as_view()),
    path('contact/<int:id>', ContactRetrieveView.as_view()),
    path('contact/new', ContactCreateView.as_view()),
    path('contact/update/<int:id>', ContactUpdateView.as_view()),
    path('contact/delete/<int:id>', ContactDeleteView.as_view()),
    path('feedback/<int:id>', FeedbackRetrieveView.as_view()),
    path('feedback/new', FeedbackCreateView.as_view()),
    path('feedback/update/<int:id>', FeedbackUpdateView.as_view()),
    path('feedback/delete/<int:id>', FeedbackDeleteView.as_view()),
    path('cities/<int:id>', CitiesRetrieveView.as_view()),
    path('cities/new', CitiesCreateView.as_view()),
    path('cities/update/<int:id>', CitiesUpdateView.as_view()),
    path('cities/delete/<int:id>', CitiesDeleteView.as_view()),    
    path('bloodgroup/<int:id>', BloodgroupRetrieveView.as_view()),
    path('bloodgroup/new', BloodgroupCreateView.as_view()),
    path('bloodgroup/update/<int:id>', BloodgroupUpdateView.as_view()),
    path('bloodgroup/delete/<int:id>', BloodgroupDeleteView.as_view()),
    path('countries/<int:id>', CountriesRetrieveView.as_view()),
    path('countries/new', CountriesCreateView.as_view()),
    path('countries/update/<int:id>', CountriesUpdateView.as_view()),
    path('countries/delete/<int:id>', CountriesDeleteView.as_view()),
    path('currencies/<int:id>', CurrenciesRetrieveView.as_view()),
    path('currencies/new', CurrenciesCreateView.as_view()),
    path('currencies/update/<int:id>', CurrenciesUpdateView.as_view()),
    path('currencies/delete/<int:id>', CurrenciesDeleteView.as_view()),
    path('social/<int:id>', SocialRetrieveView.as_view()),
    path('social/new', SocialCreateView.as_view()),
    path('social/update/<int:id>', SocialUpdateView.as_view()),
    path('social/delete/<int:id>', SocialDeleteView.as_view()),
  
]

