from django.urls import path
from .views import *

urlpatterns = [
    path('list', ExamsListView.as_view()),
    path('<int:id>', ExamDetailView.as_view()),
    path('new', ExamCreateView.as_view()),
    path('<int:examId>/subjectList', SubjectsListView.as_view()),
    path('<int:examId>/subject/<int:id>', SubjectDetailView.as_view()),
    path('<int:examId>/subject/new', SubjectCreateView.as_view()),
    path('<int:examId>/subject/<int:subjectId>/questionList', QuestionsListView.as_view()),
    path('<int:examId>/subject/<int:subjectId>/question/<int:id>', QuestionDetailView.as_view()),
    path('<int:examId>/subject/<int:subjectId>/question/new', QuestionCreateView.as_view()),
    path('<int:id>/start', StartedView.as_view()),
    path('<int:id>/enroll', EnrollMentView.as_view()),
    path('<int:examId>/<int:subjectId>/question/<int:qid>/answer/selected_option=<int:option>', AnsweredView.as_view()),
    path('address/<int:id>', AddressRetrieveView.as_view()),
    path('address/new', AddressCreateView.as_view()),
    path('address/update/<int:id>', AddressUpdateView.as_view()),
    path('address/delete/<int:id>', AddressDeleteView.as_view()),  
    path('cities/<int:id>', CitiesRetrieveView.as_view()),
    path('cities/new', CitiesCreateView.as_view()),
    path('cities/update/<int:id>', CitiesUpdateView.as_view()),
    path('cities/delete/<int:id>', CitiesDeleteView.as_view()),    
    path('bloodgroup/<int:id>', BloodgroupRetrieveView.as_view()),
    path('bloodgroup/new', BloodgroupCreateView.as_view()),
    path('bloodgroup/update/<int:id>', BloodgroupUpdateView.as_view()),
    path('bloodgroup/delete/<int:id>', BloodgroupDeleteView.as_view()),
    path('countries/<int:id>', CountriesRetrieveView.as_view()),
    path('countries/new', CountriesCreateView.as_view()),
    path('countries/update/<int:id>', CountriesUpdateView.as_view()),
    path('countries/delete/<int:id>', CountriesDeleteView.as_view()),
    path('currencies/<int:id>', CurrenciesRetrieveView.as_view()),
    path('currencies/new', CurrenciesCreateView.as_view()),
    path('currencies/update/<int:id>', CurrenciesUpdateView.as_view()),
    path('currencies/delete/<int:id>', CurrenciesDeleteView.as_view()),    
    
]
