# Generated by Django 3.1 on 2020-10-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.cities'),
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.countries'),
        ),
    ]
