# Generated by Django 3.1 on 2020-11-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_auto_20201027_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='user',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='user',
        ),
    ]
