# Generated by Django 3.1 on 2020-11-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_auto_20201109_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='blood_group',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bloodgroup',
        ),
    ]
