# Generated by Django 3.1 on 2020-11-09 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userInfo', '0004_auto_20201109_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
